# -*- coding: utf-8 -*-
"""NotDefterim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WexBdTZ2hLxu__VMgZ_7ooPJ2npp3FYq
"""

import time

not_defteri = []

def secenekler():
    print("Not Defteri Uygulaması")
    print("1 - Yeni Not Ekle")
    print("2 - Notları Görüntüle")
    print("3 - Notu Sil")
    print("4 - Çıkış")

def not_ekle():
    current_time = time.localtime()
    formatted_time = time.strftime("%Y-%m-%d")
    yeni_not = input("Eklemek istediğiniz notu giriniz : ")
    not_defteri.append(yeni_not)
    not_defteri.append(formatted_time)
    print(f"'{formatted_time}'tarihinde Başarıyla Not Defterine Eklendi ")

def notlari_goruntule():
   if not not_defteri:
       print("Not Defteri Boş")
   else:
       print("\nNotlarınız\n")
       for i, not_ in enumerate(not_defteri,1):
          print(f"{i}.{not_}")

def not_sil():
    not_no = int(input("Lütfen silmek istediğiniz notun numarasını giriniz :")) - 1
    if 0<= not_no < len(not_defteri):
      silinen_not = not_defteri.pop(not_no)
      print(f"'{silinen_not}'basarıyla silindi ")
    else:
      print("Geçersiz not nnuması girdiniz.Lutfen tekrar deneyin...")

while True:
     secenekler()
     secim = int(input("Lütfen yapmak istediğiniz işlemi seçiniz : "))

     if secim == 1:
       not_ekle()
     elif secim == 2:
       notlari_goruntule()
     elif secim == 3:
       not_sil()
     elif secim == 4:
       print("Not defterinden çıkılıyor... ")
       break
     else:
       print("Geçersiz seçim yaptınız. Lütfen tekrar deneyin... ")